#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#eval "$(rbenv init -)"
alias findhere='mdfind -onlyin .'

export DS_DOMAIN='/Active Directory/MYEAB/All Domains'

export AWS_PROFILE=awseabmgmt
AWS_ALL_PROFILES=('awseabmgmt' 'awseabmgmtdev' 'awseabdev' 'awseabprod' 'awseabrddev' 'awseabrdprod' 'gradesfirst' 'gradesfirstdev'\
	'awseabsgddev' 'awseabsgdprod' 'awseabscsdev' 'awseabscsprod' 'awseabscadev' 'awseabscaprod')

export AWS_SDK_LOAD_CONFIG=true

aws_sudo() {
	creds=$(aws sts get-federation-token --name $1 --query 'Credentials.[SecretAccessKey, SessionToken, AccessKeyId]' --output text)
	read -r AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_ACCESS_KEY_ID <<< "$creds"
	export AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_ACCESS_KEY_ID
}

aws_role() {
	creds=$(aws sts assume-role --role-arn $1 --role-session-name cli-assume-role-`date +%s` --query 'Credentials.[SecretAccessKey, SessionToken, AccessKeyId]' --output text)
	read -r AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_ACCESS_KEY_ID <<< "$creds"
	export AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_ACCESS_KEY_ID
}

aws_reset() {
	unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
	[[ $1 = "all" ]] && unset AWS_PROFILE || echo Preserving AWS_PROFILE
}

aws_stacks() {
	aws cloudformation describe-stacks --query 'Stacks[].[StackName]' --output text
}

aws_facts() {
	aws ssm get-parameters-by-path \
	--path '/devops' \
	--recursive \
	--query 'Parameters[].[Name, Value]' \
	--output table
}

aws_accounts() {
	if (( $+1 )); then
		fn="?contains(Id, to_string(\`$1\`))"
	else
		fn=""
	fi;
	aws --profile awseabmaster organizations list-accounts \
	--query "Accounts[$fn].[Id, Email, Name]" \
	--output table
}

aws_who() {
	echo "AWS_PROFILE: $AWS_PROFILE"
	echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
	echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
	echo "AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN"
	aws sts get-caller-identity
}

ad_groups() {
	dscl "${DS_DOMAIN}" \
		read \
		Users/${1} \
		memberOf
}

ad_search() {
	dscl ${DS_DOMAIN} \
		search \
		Users \
		sn \
	        ${1} 
}

ad_members() {
	dscl "${DS_DOMAIN}" \
		read \
		"Groups/${1}" \
		dsAttrTypeNative:member
}

read_env() {
	set -a
	source $1
	set +a
}
